### ISSUE TITLE
bentoctl build issue

### ISSUE THREAD

**Issue by julianxywu** [bentoml/azure-container-instances-deploy#10]
Getting this error when trying to build an azure container. 

`FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/h8/lt9wstdd0rvbxz2yzzsjpwmr0000gn/T/tmpo41228pufsTempFS/'`

**Comment by julianxywu** [comment]
Is there a specific Python version that it supports? The error comes from `subprocess.py` from python3.9

**Comment by erenovic** [comment]
I faced the same issue when I tried to build an Azure container, too. The Bento file is under `/Users/<username>/bentoml/bentos` but I am not sure whether the build is looking for the bento.

**Comment by hade94** [comment]
I've got the same error.

Any idea?

**Comment by rukmal** [comment]
+1 on this. Same error.

**Comment by hade94** [comment]
pip install bentoctl==0.3.4 fixes this issue temporally 

I think this is not the proper repo for this issue. Should be created in https://github.com/bentoml/bentoctl

**Comment by hade94** [comment]
In debug mode. Intermediate bento saved to /tmp/bentoctl-temp-l6cs06tg
Traceback (most recent call last):
  File "/home/loginuser/anaconda3/envs/bentoml/bin/bentoctl", line 8, in <module>
    sys.exit(bentoctl())
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoctl/cli/utils.py", line 92, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoctl/cli/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoctl/cli/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoctl/cli/__init__.py", line 316, in build
    generate_deployable_container(
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoctl/docker_utils.py", line 120, in generate_deployable_container
    backend.build(**buildx_args)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoml/_internal/container/base.py", line 186, in build
    return subprocess.check_output(commands, cwd=context_path, env=env)
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/loginuser/anaconda3/envs/bentoml/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpcshobl_6fsTempFS/'

**Comment by rukmal** [comment]
@hade94 that's happening because you're using the wrong container version ID.

Run `bentoml build`, grab the image ID (or use `docker image ls | head`), and then call `bentoctl build <image>:<version_id> ...`.

Orthogonal to this, it looks like ACR is having an issue that is preventing the push stage of this process to fail with: `Error [BentoctlDockerException]:  Failed to push docker image. unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.`

See: https://github.com/Azure/azure-cli/issues/27487

**Comment by hade94** [comment]
@rukmal  i am doing exact the the things you mention. Still the same error

**Comment by BaptisteLoquette** [comment]
+1 Same error
